export const SET_USER_NICKNAME_SUCCESS = "SET_USER_NICKNAME_SUCCESS";
export const SET_USER_NICKNAME_FAILURE = "SET_USER_NICKNAME_FAILURE";
export const SET_USER_NICKNAME_RESET = "SET_USER_NICKNAME_RESET";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
